name: retrieve-logs 
on:
  workflow_dispatch:  # Triggered when a workflow is triggered
   
#  types:
 #   - completed # The logs are available only when the workflow is completed

jobs:
  retrive_workflow_logs:
    runs-on: ubuntu-latest
    name: retrieve_logs
    steps:
      - name: retrieve_workflow_logs_action
        id: retrieve_workflow_logs_action
        uses: Superbasil3/retrieve-workflow-logs-action@draft
